/* Database schema to keep the structure of entire database. */

/* animals table */
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  date_of_birth DATE,
  escape_attempts INT,
  neutered BOOLEAN,
  weight_kg DECIMAL,
  PRIMARY KEY(id)
);

ALTER TABLE animals
ADD COLUMN species VARCHAR(100);

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT;

ALTER TABLE animals
ADD FOREIGN KEY (species_id) REFERENCES species(id)
ON DELETE CASCADE;

ALTER TABLE animals
ADD COLUMN owner_id INT;

ALTER TABLE animals
ADD FOREIGN KEY (owner_id) REFERENCES owners(id)
ON DELETE CASCADE;

/* owners table */
CREATE TABLE owners (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(100),
  age INT,
  PRIMARY KEY(id)
);

/* species table */
CREATE TABLE species (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  PRIMARY KEY(id)
);

/* vets table */
CREATE TABLE vets (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  age INT,
  date_of_graduation DATE,
  PRIMARY KEY(id)
);

/* specializations table */
CREATE TABLE specializations (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  vets_id INT,
  species_id INT,
  PRIMARY KEY(id),
  FOREIGN KEY (vets_id) REFERENCES vets(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (species_id) REFERENCES species(id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* visits table */
CREATE TABLE visits (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  vets_id INT,
  animals_id INT,
  date_of_visit DATE,
  PRIMARY KEY(id),
  FOREIGN KEY (vets_id) REFERENCES vets(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (animals_id) REFERENCES animals(id) ON UPDATE CASCADE ON DELETE CASCADE
);

